### ISSUE TITLE
"world time via buttons" Request

### ISSUE THREAD

**Issue by jsonnet** [austinv11/CollectiveFramework#1]
> It is just a Request there is no need to change code!

My Request refers to the registered buttons in the options: Is there a possible solution to hide/ not register any buttons in the controls menu, when this feature is disabled in the config?

~Josh

**Comment by austinv11** [comment]
Should be doable

**Comment by jsonnet** [comment]
Thanks, just looked it up in [Keybindings.java](http://github.com/austinv11/CollectiveFramework/blob/master/src/main/java/com/austinv11/collectiveframework/minecraft/init/Keybindings.java)
It shouldn't be more than an if statement I guess

~Josh
