### ISSUE TITLE
Can't join in my server

### ISSUE THREAD

**Issue by AlexPlus117** [austinv11/CollectiveFramework#2]
Hi austin, I can't join in my server and this is a part of the log: http://pastebin.com/z6Me0vzk
EDIT: It seems not to be a your mod bug, but a RFTools one.

**Comment by austinv11** [comment]
Let me know if there are still problems

**Comment by AlexPlus117** [comment]
Yes, there are still problems! I spoke with the author of RFTools and he said it's not a bug of his mod, but something I've updated/installed. Read here please: https://github.com/McJty/RFTools/issues/364
I don't know what to do...

**Comment by AlexPlus117** [comment]
I've just disabled Binnie's mods and all works now.
